In [1]:
import pandas as pd

df_films = pd.read_csv("../../datasets/csv/films.csv")
df_people = pd.read_csv("../../datasets/csv/people.csv")

<h1>
Count the total number of records in the people table, aliasing the result as
count_records.
</h1>

In [6]:
display(pd.DataFrame({"count_records": [df_people.shape[0]]}))

   count_records
0           8397

<h1>
Count the number of birthdates in the people table.
</h1>

In [8]:
display(pd.DataFrame({"count_birthdate": [df_people["birthdate"].count()]}))

   count_birthdate
0             6152

<h1>
Count the records for languages and countries represented in the films table.
</h1>

In [9]:
display(
    pd.DataFrame(
        {
            "count_languages": [df_films["language"].count()],
            "count_countries": [df_films["country"].count()],
        }
    )
)

   count_languages  count_countries
0             4955             4966